networks:
  api-network:

services:
  api_backend:
    build: 
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - NODE_ENV=production
      - DATABASE_HOST=poke-db
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASS=pass
      - DATABASE_NAME=poke_db
      - API_KEY=test
    depends_on:
      - 'poke-db'
    networks:
      - api-network

  poke-db:
    image: postgres:14.7
    container_name: poke-postgres-db
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    networks:
      api-network:
volumes:
  postgres_data:
    driver: local
